feat: согласно ТЗ 11 и 12 спринта
alekseybch/java-filmorate pull request #4
Opened 2022-10-19 12:16 UTC by alekseybch

2022-10-19 23:43 UTC, NikolaiDem requested changes

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/AbstractService.java
> +    DataStorage<T> storage;
private final DataStorage<T> storage;

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +    private static final String SQL_GET_FILM_BY_ID = "SELECT f.film_id, f.film_name, f.description, f.release_date, " +
Можно вместо перечисления всех полей использовать f.*

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            без очистки жанров, невозможно пройти тест постмана из-за неверного порядка
Какой тест?
Можно попробовать использовать LinkedHashSet для жанров в Film для сохранения их порядка.

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            jdbcTemplate.update(SQL_ADD_LIKE, film.getId(), like);
При обновлении нескольких строк таблицы лучше использовать методы пакетного обновления, например, jdbcTemplate.batchUpdate(...)
Аналогично для saveGenres(...)

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Еще нужно добавить метод удаления фильма и определить такой метод в контроллере.

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/user/UserDbStorage.java
> +public class UserDbStorage implements UserStorage {
Еще нужно добавить метод удаления пользователя и определить такой метод в контроллере.

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count <= 0) throw new IllegalArgumentException(String.format("Must be positive count = %d", count));
Чтобы не получать все фильмы из БД, лучше сделать их сортировку и ограничение по количеству на уровне SQL-запроса.

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(this::getById)
Для минимизации количества запросов к БД можно найти список друзей пользователя и его общих друзей одним SQL-запросом, возвращающим List:
jdbcTemplate.query(...)

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            List<Genre> genreList = jdbcTemplate.query(SQL_GET_GENRE_BY_ID, this::mapRowToGenre, genres.getInt("genre_id"));
С помощью джойна можно сразу получить жанры фильма в одном запросе)

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/user/UserDbStorage.java
> +            jdbcTemplate.update(SQL_ADD_FRIEND, user.getId(), friendId);
При обновлении нескольких строк таблицы лучше использовать методы пакетного обновления, например, jdbcTemplate.batchUpdate(...)

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users CASCADE;
Зачем удалять таблицы?)
Если необходимо только для тестов, то лучше в тестах использовать @AutoConfigureTestDatabase

2022-10-19 23:43 UTC, NikolaiDem commented on src/main/resources/data.sql
> +INSERT INTO genres (genre_name) VALUES ('Комедия');
Чтобы не было ошибок нарушения целостности первичного ключа, лучше использовать MERGE INTO

2022-10-21 12:33 UTC, alekseybch commented
-Заменен INSERT INTO на MERGE INTO в data.sql
-Убраны удаляющие таблицу команды в schema.sql
-Изменена логика сохранения друзей, вместо метода saveFriends, теперь addFriend и deleteFriend
-Доработан sql запрос на получение жанров в getGenres
-Переделан getFriends, метод выполняется одним запросом к БД
-Добавлены методы удаления для пользоватей и фильмов, а так же контроллеры обращения к ним
-Изменена логика сохранения лайков, вместо метода saveLikes, теперь addLike и deleteLike
-В saveGenres заменен jdbcTemplate.update в цикле на jdbcTemplate.batchUpdate

2022-10-21 13:15 UTC, alekseybch commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            без очистки жанров, невозможно пройти тест постмана из-за неверного порядка
С LinkedHashSet такая же проблема, похоже при сереализации игнорируется порядок
Получается без очистки и повторного заполнения, порядок возврата в постман тесте "Friend film genres update with duplicate" не выполняется

2022-10-21 22:55 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            без очистки жанров, невозможно пройти тест постмана из-за неверного порядка
Jackson при парсинге json-а смотрит лишь на тип поля (в нашем случае Set) и создает по умолчанию HashSet (для интерфейса сета). Поэтому можно определить тип поля genres в Film как LinkedHashSet, тогда Jackson создаст LinkedHashSet, и порядок жанров в сете будет корректным. Для TreeSet можно написать кастомный десериалайзер)

2022-10-21 22:55 UTC, NikolaiDem approved these changes

2022-10-22 07:15 UTC, merged